// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7OM5Cd28GTxV9SngPjNWa2PoGM5PxAiA',
    appId: '1:1031882559547:web:369ccd9868e879dd804c1e',
    messagingSenderId: '1031882559547',
    projectId: 'mortal-combat-3af66',
    authDomain: 'mortal-combat-3af66.firebaseapp.com',
    storageBucket: 'mortal-combat-3af66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv1bHxN-zEJ9Lo8JJa05Fe8Z4M5Q1T8UY',
    appId: '1:1031882559547:android:c2e7024dfe5c38e4804c1e',
    messagingSenderId: '1031882559547',
    projectId: 'mortal-combat-3af66',
    storageBucket: 'mortal-combat-3af66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0cd52gISGWwj7Dc1d0xVwAxxUZnpsIQ',
    appId: '1:1031882559547:ios:62e464780d06ff36804c1e',
    messagingSenderId: '1031882559547',
    projectId: 'mortal-combat-3af66',
    storageBucket: 'mortal-combat-3af66.appspot.com',
    iosClientId: '1031882559547-fob5ouqh5tabpiucchv9phrhuoe0ek92.apps.googleusercontent.com',
    iosBundleId: 'com.example.mortalCombat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK0cd52gISGWwj7Dc1d0xVwAxxUZnpsIQ',
    appId: '1:1031882559547:ios:1247f86b2b050b2a804c1e',
    messagingSenderId: '1031882559547',
    projectId: 'mortal-combat-3af66',
    storageBucket: 'mortal-combat-3af66.appspot.com',
    iosClientId: '1031882559547-e40nm7hgtc5u14k073bvi2sgnbscpbd4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mortalCombat.RunnerTests',
  );
}
